### ISSUE TITLE
Deployments failing with container image 3.116.1

### ISSUE THREAD

**Issue by pylaligand** [pulumi/console-requests#389] opened 2024-05-15 21:10 UTC
Deployments started failing earlier today at the "Download dependencies" stage due to a Python environment setup error:
```
$ /pulumi-deploy-executor dependencies download --workDir="/deployment/github-repo-config" 
The virtual environment was not created successfully because ensurepip is not 
available.  On Debian/Ubuntu systems, you need to install the python3-venv 
package using the following command. 
 
   apt-get install python3-venv 
 
You may need to use sudo with that command.  After installing the python3-venv 
package, recreate your virtual environment. 
 
Failing command: ['/deployment/github-repo-config/venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip'] 
 
Error: command finished with error: exit status 1 
```

## Expected behavior

Deployments complete successfully.

## Current behavior

Deployments fail early at the setup stage.

## Steps to reproduce

1. Create a deployment
2. Watch it fail early

## Context (Environment)

Our last successful deployment started with:
```
Preparing environment 
Pulling container image "pulumi/pulumi:3.115.2" 
3.115.2: Pulling from pulumi/pulumi 
Digest: sha256:a7b9022d7c1a40d81adeca30a21eb1cd49add474e3de923ade663db046e7ee1a 
Status: Downloaded newer image for pulumi/pulumi:3.115.2 
Starting container 
Container created (b3caed9741a27213ebb7f135fbdcdecef08d9e5c3163b4e587baf548a2b622d1) 
Container started (b3caed9741a27213ebb7f135fbdcdecef08d9e5c3163b4e587baf548a2b622d1) 
```

Subsequent failures have:
```
Preparing environment 
Pulling container image "pulumi/pulumi:3.116.1" 
3.116.1: Pulling from pulumi/pulumi 
Digest: sha256:8e3b00713fabf9e93c5b5cb27c6a73a56fec30d56b71ca00dd479fe71b566daa 
Status: Downloaded newer image for pulumi/pulumi:3.116.1 
Starting container 
Container created (8de0159cac1945be6fb2f03f59473476bdd709c56c3bf2172c67926121a6f821) 
Container started (8de0159cac1945be6fb2f03f59473476bdd709c56c3bf2172c67926121a6f821)
```

It looks like 3.116.1 was released today.

I manually set the executor image to `pulumi/pulumi:3.115.2` in my project and the next deployment succeeded.

## Affected feature

Deployments.

**Comment by komalali** [comment] 2024-05-15 21:52
Thanks for this issue! This is a duplicate of https://github.com/pulumi/pulumi-docker-containers/issues/193

We have a fix rolling out for deployments to pin to v3.115.2 until the issue linked is resolved. I'm going to close this as a dup but you can follow https://github.com/pulumi/pulumi-docker-containers/issues/193 for updates.

**Closed as completed by komalali** 2024-05-15 21:52 UTC
Labels: resolution/duplicate, customer/feedback
