### ISSUE TITLE
Unable to access Pulumi ECS environments for the last 24 hours

### ISSUE THREAD

**Issue by smith558** [pulumi/console-requests#478] opened 2024-11-13 08:49 UTC
Hi. We're unable to access Pulumi ECS environments for the last 24 hours. This has now completely blocked us. There are no connection or quality issues on our network.

![Image](https://github.com/user-attachments/assets/bf9f9276-17f6-4476-99b6-84ae0e1d3910)

**Comment by smith558** [comment] 2024-11-13 08:51
@pierskarsenbarg @meagancojocar @danielrbradley

**Comment by smith558** [comment] 2024-11-13 08:53
identical to https://github.com/pulumi/pulumi-cloud-requests/issues/477

**Comment by pierskarsenbarg** [comment] 2024-11-13 09:00
@smith558 Can you please stop tagging multiple people in these issues. I'm closing this one as a duplicate of #477 (as that was opened first) and I will respond in that issue.

**Closed as completed by pierskarsenbarg** 2024-11-13 09:00 UTC
Labels: resolution/duplicate

**Comment by smith558** [comment] 2024-11-13 09:04
> [@smith558](https://github.com/smith558) Can you please stop tagging multiple people in these issues. I'm closing this one as a duplicate of [#477](https://github.com/pulumi/pulumi-cloud-requests/issues/477) (as that was opened first) and I will respond in that issue.

With due respect. (it seems) Most issues on this GitHub tracker have been without a response for weeks. I had to try something.

**Comment by pierskarsenbarg** [comment] 2024-11-13 09:09
If you have an issue or support request, you should email support@pulumi.com or follow the "Support" link in the footer of the Pulumi website.

**Comment by smith558** [comment] 2024-11-13 09:12
> If you have an issue or support request, you should email [support@pulumi.com](mailto:support@pulumi.com) or follow the "Support" link in the footer of the Pulumi website.

I followed the most visible instructions on https://app.pulumi.com/smodrak/esc/, there's a note that says "Send feedback now" and goes to "https://github.com/pulumi/service-requests/issues/new?assignees=&labels=customer%2Ffeedback%2Cneeds-triage&template=product-feedback.md".  I am not shown a "Support" link in that view. This may or may not be up to date.

**Comment by pierskarsenbarg** [comment] 2024-11-13 10:00
Yes I've noticed that this morning as well. I'm in conversation with the engineering team to improve the links to support.

>With due respect. (it seems) Most issues on this GitHub tracker have been without a response for weeks. I had to try something.

The majority of the issues here are feature requests rather than bug reports, which is probably why you don't see as many responses. - if we have questions we'll ask otherwise these items go into our road map to be prioritised internally

**Comment by smith558** [comment] 2024-11-13 10:09
> Yes I've noticed that this morning as well. I'm in conversation with the engineering team to improve the links to support.
> 
> > With due respect. (it seems) Most issues on this GitHub tracker have been without a response for weeks. I had to try something.
> 
> The majority of the issues here are feature requests rather than bug reports, which is probably why you don't see as many responses. - if we have questions we'll ask otherwise these items go into our road map to be prioritised internally

You're right. Upon closer look, they're indeed feature requests.
