### ISSUE TITLE
Deleting a team doesn't properly redirect to `Teams` page in `Settings`

### ISSUE THREAD

**Issue by ringods** [pulumi/console-requests#407] opened 2024-06-04 14:12 UTC
## Expected behavior

After a team is deleted, the web UI should redirect back to the `Teams` page in `Settings`.

## Current behavior

1. Team is deleted and UI stays at the team url (e.g. `https://<host>/backbone/teams/test` )
2. UI displays the big Error 500 page

## Steps to reproduce

1. Create a team in an org
2. Navigate to that team and click `Remove` in the danger zone and acknowledge the deletion

## Context (Environment)

Self-hosted. Tested with `20240603-2560-signed` and `20240306-2343-signed`

## Affected feature

RBAC - Team management.

**Comment by kimberleyamackenzie** [comment] 2024-06-10 20:50
@ringods I do not repro this.  I have done the following steps a few times, including with slow 3G network connections, and have always been redirected back to the teams list page.  

1. Navigate to $orgName/teams
2. Select a team, which navigates me to $orgName/teams/$teamName
3. Scroll down to the delete section on that page, and select "Remove"
4. Confirm removal via the dialog
5. I'm automatically navigated back to $orgName/teams

Given that I have a few questions so we can narrow this down:
1. Is my above repro the correct one?  
2. Do you still repro this on your end?  If so, do you only repro via self-hosted, or can you repro on prod or elsewhere?
3. Could you open up your dev tools, and let me know what request is 500ing?  Is it the delete?

Thanks!

**Comment by kimberleyamackenzie** [comment] 2024-06-17 19:35
@ringods Checking in on the above, does this still repro for you?

**Comment by caseyyh** [comment] 2024-06-24 20:46
From slack, Ringo called out that this is potentially related: https://github.com/pulumi/pulumi-service/issues/20462

**Comment by kimberleyamackenzie** [comment] 2024-06-24 20:53
@caseyyh Agree that I think these 2 bugs are dealing with the same root cause (the panic).  I propose we close this one, since the UI has the correct logic and is just responding to the panic, and the UI's handling will be righted once the panic is fixed.

**Comment by caseyyh** [comment] 2024-06-25 18:16
Closing in favor of https://github.com/pulumi/pulumi-service/issues/20462

**Closed as completed by caseyyh** 2024-06-25 18:16 UTC
Labels: kind/bug, resolution/duplicate, customer/feedback
