### ISSUE TITLE
Pulumi Deployments runs out of memory

### ISSUE THREAD

**Issue by deni64k** [pulumi/console-requests#313] opened 2023-10-16 18:00 UTC
Pulumi Deployments runs out of memory while running preview or update.

## Expected behavior

Pulumi Deployments is expected to work as usual.

## Current behavior

Here is the error message:

```
$ /pulumi-deploy-executor pulumi preview --stackIdentity="integral/infra/production" --workDir="/deployment/projects/backend" 
2
 Previewing update (production) 
3
  
4
 View Live: https://app.pulumi.com/integral/infra/production/previews/14d282d7-b700-4f4c-adae-529e02334c30 
5
  
6
 @ Previewing update............................ 
7
  
8
 @ Previewing update..................................................................................................................................................................................................................................................................................... 
9
     pulumi:pulumi:Stack infra-production  # github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/compute 
10
     pulumi:pulumi:Stack infra-production  fatal error: runtime: out of memory 
11
     pulumi:pulumi:Stack infra-production  runtime stack: 
12
     pulumi:pulumi:Stack infra-production  runtime.throw({0xd7b769?, 0x20306f3?}) 
13
     pulumi:pulumi:Stack infra-production  	runtime/panic.go:1077 +0x5c fp=0xc00008bdb0 sp=0xc00008bd80 pc=0x444e3c 
14
     pulumi:pulumi:Stack infra-production  runtime.sysMapOS(0xc1bd400000, 0x1000000?) 
15
     pulumi:pulumi:Stack infra-production  	runtime/mem_linux.go:167 +0x116 fp=0xc00008bdf8 sp=0xc00008bdb0 pc=0x41ee76 
16
     pulumi:pulumi:Stack infra-production  runtime.sysMap(0xc0a4287720?, 0x0?, 0x4a200000?) 
17
     pulumi:pulumi:Stack infra-production  	runtime/mem.go:155 +0x34 fp=0xc00008be28 sp=0xc00008bdf8 pc=0x41e854 
18
     pulumi:pulumi:Stack infra-production  runtime.(*mheap).grow(0x145a9e0, 0x64c?) 
19
     pulumi:pulumi:Stack infra-production  	runtime/mheap.go:1533 +0x236 fp=0xc00008be98 sp=0xc00008be28 pc=0x433cb6 
20
     pulumi:pulumi:Stack infra-production  runtime.(*mheap).allocSpan(0x145a9e0, 0x64c, 0x0, 0x1e?) 
21
     pulumi:pulumi:Stack infra-production  	runtime/mheap.go:1250 +0x3ea fp=0xc00008bf80 sp=0xc00008be98 pc=0x432c6a 
22
     pulumi:pulumi:Stack infra-production  runtime.(*mheap).alloc.func1() 
23
     pulumi:pulumi:Stack infra-production  	runtime/mheap.go:968 +0x5c fp=0xc00008bfc8 sp=0xc00008bf80 pc=0x4327fc 
24
     pulumi:pulumi:Stack infra-production  traceback: unexpected SPWRITE function runtime.systemstack 
25
     pulumi:pulumi:Stack infra-production  runtime.systemstack() 
26
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:509 +0x4a fp=0xc00008bfd8 sp=0xc00008bfc8 pc=0x47b24a 
27
     pulumi:pulumi:Stack infra-production  goroutine 1 [running]: 
28
     pulumi:pulumi:Stack infra-production  runtime.systemstack_switch() 
29
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:474 +0x8 fp=0xc0a4287540 sp=0xc0a4287530 pc=0x47b1e8 
30
     pulumi:pulumi:Stack infra-production  runtime.(*mheap).alloc(0xc98000?, 0x64c?, 0xd8?) 
31
     pulumi:pulumi:Stack infra-production  	runtime/mheap.go:962 +0x5b fp=0xc0a4287588 sp=0xc0a4287540 pc=0x43275b 
32
     pulumi:pulumi:Stack infra-production  runtime.(*mcache).allocLarge(0x1472600?, 0xc98000, 0x0?) 
33
     pulumi:pulumi:Stack infra-production  	runtime/mcache.go:234 +0x85 fp=0xc0a42875d0 sp=0xc0a4287588 pc=0x41cd45 
34
     pulumi:pulumi:Stack infra-production  runtime.mallocgc(0xc98000, 0xd59d00, 0x1) 
35
     pulumi:pulumi:Stack infra-production  	runtime/malloc.go:1123 +0x565 fp=0xc0a4287648 sp=0xc0a42875d0 pc=0x4115c5 
36
     pulumi:pulumi:Stack infra-production  runtime.growslice(0xc1bc43c000, 0x1800?, 0x7f917a184108?, 0x1800?, 0xd59d00) 
37
     pulumi:pulumi:Stack infra-production  	runtime/slice.go:274 +0x510 fp=0xc0a42876b8 sp=0xc0a4287648 pc=0x45dd90 
38
     pulumi:pulumi:Stack infra-production  cmd/internal/obj.(*Link).NumberSyms.func3(0xc174a32800) 
39
     pulumi:pulumi:Stack infra-production  	cmd/internal/obj/sym.go:241 +0x199 fp=0xc0a4287730 sp=0xc0a42876b8 pc=0x56b819 
40
     pulumi:pulumi:Stack infra-production  cmd/internal/obj.(*Link).traverseSyms.func1(...) 
41
     pulumi:pulumi:Stack infra-production  	cmd/internal/obj/sym.go:352 
42
     pulumi:pulumi:Stack infra-production  cmd/internal/obj.(*Link).traverseSyms(0xc000190400, 0x9, 0xc0a4287998) 
43
     pulumi:pulumi:Stack infra-production  	cmd/internal/obj/sym.go:385 +0x644 fp=0xc0a4287900 sp=0xc0a4287730 pc=0x56c284 
44
     pulumi:pulumi:Stack infra-production  cmd/internal/obj.(*Link).NumberSyms(0xc000190400) 
45
     pulumi:pulumi:Stack infra-production  	cmd/internal/obj/sym.go:220 +0x373 fp=0xc0a42879d8 sp=0xc0a4287900 pc=0x56b2b3 
46
     pulumi:pulumi:Stack infra-production  cmd/compile/internal/gc.Main(0xda33e8) 
47
     pulumi:pulumi:Stack infra-production  	cmd/compile/internal/gc/main.go:368 +0x1765 fp=0xc0a4287ee0 sp=0xc0a42879d8 pc=0xc70bc5 
48
     pulumi:pulumi:Stack infra-production  main.main() 
49
     pulumi:pulumi:Stack infra-production  	cmd/compile/main.go:57 +0xf9 fp=0xc0a4287f40 sp=0xc0a4287ee0 pc=0xc98979 
50
     pulumi:pulumi:Stack infra-production  runtime.main() 
51
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:267 +0x2bb fp=0xc0a4287fe0 sp=0xc0a4287f40 pc=0x44785b 
52
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
53
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc0a4287fe8 sp=0xc0a4287fe0 pc=0x47d041 
54
     pulumi:pulumi:Stack infra-production  goroutine 2 [force gc (idle), 2 minutes]: 
55
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?) 
56
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc000058fa8 sp=0xc000058f88 pc=0x447cce 
57
     pulumi:pulumi:Stack infra-production  runtime.goparkunlock(...) 
58
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:404 
59
     pulumi:pulumi:Stack infra-production  runtime.forcegchelper() 
60
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:322 +0xb3 fp=0xc000058fe0 sp=0xc000058fa8 pc=0x447b33 
61
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
62
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x47d041 
63
     pulumi:pulumi:Stack infra-production  created by runtime.init.6 in goroutine 1 
64
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:310 +0x1a 
65
     pulumi:pulumi:Stack infra-production  goroutine 3 [GC sweep wait]: 
66
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x145a901?, 0x7f9130100300?, 0x0?, 0x0?, 0x0?) 
67
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc000059748 sp=0xc000059728 pc=0x447cce 
68
     pulumi:pulumi:Stack infra-production  runtime.goparkunlock(...) 
69
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:404 
70
     pulumi:pulumi:Stack infra-production  runtime.bgsweep(0x0?) 
71
     pulumi:pulumi:Stack infra-production  	runtime/mgcsweep.go:321 +0xdf fp=0xc0000597c8 sp=0xc000059748 pc=0x42e09f 
72
     pulumi:pulumi:Stack infra-production  runtime.gcenable.func1() 
73
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:200 +0x25 fp=0xc0000597e0 sp=0xc0000597c8 pc=0x421dc5 
74
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
75
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0x47d041 
76
     pulumi:pulumi:Stack infra-production  created by runtime.gcenable in goroutine 1 
77
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:200 +0x66 
78
     pulumi:pulumi:Stack infra-production  goroutine 4 [GC scavenge wait]: 
79
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x16b9e93?, 0x5cfbb8?, 0x0?, 0x0?, 0x0?) 
80
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc000059f70 sp=0xc000059f50 pc=0x447cce 
81
     pulumi:pulumi:Stack infra-production  runtime.goparkunlock(...) 
82
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:404 
83
     pulumi:pulumi:Stack infra-production  runtime.(*scavengerState).park(0x142d760) 
84
     pulumi:pulumi:Stack infra-production  	runtime/mgcscavenge.go:425 +0x49 fp=0xc000059fa0 sp=0xc000059f70 pc=0x42b6c9 
85
     pulumi:pulumi:Stack infra-production  runtime.bgscavenge(0x0?) 
86
     pulumi:pulumi:Stack infra-production  	runtime/mgcscavenge.go:658 +0x59 fp=0xc000059fc8 sp=0xc000059fa0 pc=0x42bc79 
87
     pulumi:pulumi:Stack infra-production  runtime.gcenable.func2() 
88
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:201 +0x25 fp=0xc000059fe0 sp=0xc000059fc8 pc=0x421d65 
89
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
90
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x47d041 
91
     pulumi:pulumi:Stack infra-production  created by runtime.gcenable in goroutine 1 
92
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:201 +0xa5 
93
     pulumi:pulumi:Stack infra-production  goroutine 17 [finalizer wait, 2 minutes]: 
94
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x0?, 0xc000110498?, 0x50?, 0x12?, 0x1000000010?) 
95
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc0042b6e28 sp=0xc0042b6e08 pc=0x447cce 
96
     pulumi:pulumi:Stack infra-production  runtime.runfinq() 
97
     pulumi:pulumi:Stack infra-production  	runtime/mfinal.go:193 +0x107 fp=0xc0042b6fe0 sp=0xc0042b6e28 pc=0x420e47 
98
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
99
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc0042b6fe8 sp=0xc0042b6fe0 pc=0x47d041 
100
     pulumi:pulumi:Stack infra-production  created by runtime.createfing in goroutine 1 
101
     pulumi:pulumi:Stack infra-production  	runtime/mfinal.go:163 +0x3d 
102
     pulumi:pulumi:Stack infra-production  goroutine 209 [GC worker (idle)]: 
103
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x1472600?, 0x2?, 0x8d?, 0xd6?, 0xc1cf80?) 
104
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc00044bf50 sp=0xc00044bf30 pc=0x447cce 
105
     pulumi:pulumi:Stack infra-production  runtime.gcBgMarkWorker() 
106
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:1293 +0xe5 fp=0xc00044bfe0 sp=0xc00044bf50 pc=0x423a85 
107
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
108
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc00044bfe8 sp=0xc00044bfe0 pc=0x47d041 
109
     pulumi:pulumi:Stack infra-production  created by runtime.gcBgMarkStartWorkers in goroutine 144 
110
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:1217 +0x1c 
111
     pulumi:pulumi:Stack infra-production  goroutine 197 [select]: 
112
     pulumi:pulumi:Stack infra-production  runtime.gopark(0xc158a53fb0?, 0x2?, 0x2?, 0x0?, 0xc158a53f6c?) 
113
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc158a53dc0 sp=0xc158a53da0 pc=0x447cce 
114
     pulumi:pulumi:Stack infra-production  runtime.selectgo(0xc158a53fb0, 0xc158a53f68, 0x0?, 0x0, 0x2?, 0x1) 
115
     pulumi:pulumi:Stack infra-production  	runtime/select.go:327 +0x725 fp=0xc158a53ee0 sp=0xc158a53dc0 pc=0x458cc5 
116
     pulumi:pulumi:Stack infra-production  cmd/compile/internal/gc.compileFunctions.func3() 
117
     pulumi:pulumi:Stack infra-production  	cmd/compile/internal/gc/compile.go:154 +0x126 fp=0xc158a53fe0 sp=0xc158a53ee0 pc=0xc6eb86 
118
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
119
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc158a53fe8 sp=0xc158a53fe0 pc=0x47d041 
120
     pulumi:pulumi:Stack infra-production  created by cmd/compile/internal/gc.compileFunctions in goroutine 1 
121
     pulumi:pulumi:Stack infra-production  	cmd/compile/internal/gc/compile.go:147 +0xf1 
122
     pulumi:pulumi:Stack infra-production  goroutine 210 [GC worker (idle)]: 
123
     pulumi:pulumi:Stack infra-production  runtime.gopark(0x378ef43b443?, 0x2?, 0xd8?, 0xc0?, 0x0?) 
124
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc00044b750 sp=0xc00044b730 pc=0x447cce 
125
     pulumi:pulumi:Stack infra-production  runtime.gcBgMarkWorker() 
126
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:1293 +0xe5 fp=0xc00044b7e0 sp=0xc00044b750 pc=0x423a85 
127
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
128
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc00044b7e8 sp=0xc00044b7e0 pc=0x47d041 
129
     pulumi:pulumi:Stack infra-production  created by runtime.gcBgMarkStartWorkers in goroutine 144 
130
     pulumi:pulumi:Stack infra-production  	runtime/mgc.go:1217 +0x1c 
131
     pulumi:pulumi:Stack infra-production  goroutine 231898 [select]: 
132
     pulumi:pulumi:Stack infra-production  runtime.gopark(0xc000054fb0?, 0x2?, 0x4?, 0x0?, 0xc000054f6c?) 
133
     pulumi:pulumi:Stack infra-production  	runtime/proc.go:398 +0xce fp=0xc000054dc0 sp=0xc000054da0 pc=0x447cce 
134
     pulumi:pulumi:Stack infra-production  runtime.selectgo(0xc000054fb0, 0xc000054f68, 0xc0009c07e0?, 0x0, 0xccb4c0?, 0x1) 
135
     pulumi:pulumi:Stack infra-production  	runtime/select.go:327 +0x725 fp=0xc000054ee0 sp=0xc000054dc0 pc=0x458cc5 
136
     pulumi:pulumi:Stack infra-production  cmd/compile/internal/gc.compileFunctions.func3() 
137
     pulumi:pulumi:Stack infra-production  	cmd/compile/internal/gc/compile.go:154 +0x126 fp=0xc000054fe0 sp=0xc000054ee0 pc=0xc6eb86 
138
     pulumi:pulumi:Stack infra-production  runtime.goexit() 
139
     pulumi:pulumi:Stack infra-production  	runtime/asm_amd64.s:1650 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x47d041 
140
     pulumi:pulumi:Stack infra-production  created by cmd/compile/internal/gc.compileFunctions in goroutine 1 
141
     pulumi:pulumi:Stack infra-production  	cmd/compile/internal/gc/compile.go:147 +0xf1 
142
 @ Previewing update.... 
143
     pulumi:pulumi:Stack infra-production  error: error in compiling Go: unable to run `go build`: exit status 1 
144
     pulumi:pulumi:Stack infra-production  1 error; 133 messages 
145
 Diagnostics: 
146
   pulumi:pulumi:Stack (infra-production): 
147
     error: error in compiling Go: unable to run `go build`: exit status 1 
148
  
149
     # github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/compute 
150
     fatal error: runtime: out of memory 
151
     runtime stack: 
152
     runtime.throw({0xd7b769?, 0x20306f3?}) 
153
     	runtime/panic.go:1077 +0x5c fp=0xc00008bdb0 sp=0xc00008bd80 pc=0x444e3c 
154
     runtime.sysMapOS(0xc1bd400000, 0x1000000?) 
155
     	runtime/mem_linux.go:167 +0x116 fp=0xc00008bdf8 sp=0xc00008bdb0 pc=0x41ee76 
156
     runtime.sysMap(0xc0a4287720?, 0x0?, 0x4a200000?) 
157
     	runtime/mem.go:155 +0x34 fp=0xc00008be28 sp=0xc00008bdf8 pc=0x41e854 
158
     runtime.(*mheap).grow(0x145a9e0, 0x64c?) 
159
     	runtime/mheap.go:1533 +0x236 fp=0xc00008be98 sp=0xc00008be28 pc=0x433cb6 
160
     runtime.(*mheap).allocSpan(0x145a9e0, 0x64c, 0x0, 0x1e?) 
161
     	runtime/mheap.go:1250 +0x3ea fp=0xc00008bf80 sp=0xc00008be98 pc=0x432c6a 
162
     runtime.(*mheap).alloc.func1() 
163
     	runtime/mheap.go:968 +0x5c fp=0xc00008bfc8 sp=0xc00008bf80 pc=0x4327fc 
164
     traceback: unexpected SPWRITE function runtime.systemstack 
165
     runtime.systemstack() 
166
     	runtime/asm_amd64.s:509 +0x4a fp=0xc00008bfd8 sp=0xc00008bfc8 pc=0x47b24a 
167
     goroutine 1 [running]: 
168
     runtime.systemstack_switch() 
169
     	runtime/asm_amd64.s:474 +0x8 fp=0xc0a4287540 sp=0xc0a4287530 pc=0x47b1e8 
170
     runtime.(*mheap).alloc(0xc98000?, 0x64c?, 0xd8?) 
171
     	runtime/mheap.go:962 +0x5b fp=0xc0a4287588 sp=0xc0a4287540 pc=0x43275b 
172
     runtime.(*mcache).allocLarge(0x1472600?, 0xc98000, 0x0?) 
173
     	runtime/mcache.go:234 +0x85 fp=0xc0a42875d0 sp=0xc0a4287588 pc=0x41cd45 
174
     runtime.mallocgc(0xc98000, 0xd59d00, 0x1) 
175
     	runtime/malloc.go:1123 +0x565 fp=0xc0a4287648 sp=0xc0a42875d0 pc=0x4115c5 
176
     runtime.growslice(0xc1bc43c000, 0x1800?, 0x7f917a184108?, 0x1800?, 0xd59d00) 
177
     	runtime/slice.go:274 +0x510 fp=0xc0a42876b8 sp=0xc0a4287648 pc=0x45dd90 
178
     cmd/internal/obj.(*Link).NumberSyms.func3(0xc174a32800) 
179
     	cmd/internal/obj/sym.go:241 +0x199 fp=0xc0a4287730 sp=0xc0a42876b8 pc=0x56b819 
180
     cmd/internal/obj.(*Link).traverseSyms.func1(...) 
181
     	cmd/internal/obj/sym.go:352 
182
     cmd/internal/obj.(*Link).traverseSyms(0xc000190400, 0x9, 0xc0a4287998) 
183
     	cmd/internal/obj/sym.go:385 +0x644 fp=0xc0a4287900 sp=0xc0a4287730 pc=0x56c284 
184
     cmd/internal/obj.(*Link).NumberSyms(0xc000190400) 
185
     	cmd/internal/obj/sym.go:220 +0x373 fp=0xc0a42879d8 sp=0xc0a4287900 pc=0x56b2b3 
186
     cmd/compile/internal/gc.Main(0xda33e8) 
187
     	cmd/compile/internal/gc/main.go:368 +0x1765 fp=0xc0a4287ee0 sp=0xc0a42879d8 pc=0xc70bc5 
188
     main.main() 
189
     	cmd/compile/main.go:57 +0xf9 fp=0xc0a4287f40 sp=0xc0a4287ee0 pc=0xc98979 
190
     runtime.main() 
191
     	runtime/proc.go:267 +0x2bb fp=0xc0a4287fe0 sp=0xc0a4287f40 pc=0x44785b 
192
     runtime.goexit() 
193
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc0a4287fe8 sp=0xc0a4287fe0 pc=0x47d041 
194
     goroutine 2 [force gc (idle), 2 minutes]: 
195
     runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?) 
196
     	runtime/proc.go:398 +0xce fp=0xc000058fa8 sp=0xc000058f88 pc=0x447cce 
197
     runtime.goparkunlock(...) 
198
     	runtime/proc.go:404 
199
     runtime.forcegchelper() 
200
     	runtime/proc.go:322 +0xb3 fp=0xc000058fe0 sp=0xc000058fa8 pc=0x447b33 
201
     runtime.goexit() 
202
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc000058fe8 sp=0xc000058fe0 pc=0x47d041 
203
     created by runtime.init.6 in goroutine 1 
204
     	runtime/proc.go:310 +0x1a 
205
     goroutine 3 [GC sweep wait]: 
206
     runtime.gopark(0x145a901?, 0x7f9130100300?, 0x0?, 0x0?, 0x0?) 
207
     	runtime/proc.go:398 +0xce fp=0xc000059748 sp=0xc000059728 pc=0x447cce 
208
     runtime.goparkunlock(...) 
209
     	runtime/proc.go:404 
210
     runtime.bgsweep(0x0?) 
211
     	runtime/mgcsweep.go:321 +0xdf fp=0xc0000597c8 sp=0xc000059748 pc=0x42e09f 
212
     runtime.gcenable.func1() 
213
     	runtime/mgc.go:200 +0x25 fp=0xc0000597e0 sp=0xc0000597c8 pc=0x421dc5 
214
     runtime.goexit() 
215
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc0000597e8 sp=0xc0000597e0 pc=0x47d041 
216
     created by runtime.gcenable in goroutine 1 
217
     	runtime/mgc.go:200 +0x66 
218
     goroutine 4 [GC scavenge wait]: 
219
     runtime.gopark(0x16b9e93?, 0x5cfbb8?, 0x0?, 0x0?, 0x0?) 
220
     	runtime/proc.go:398 +0xce fp=0xc000059f70 sp=0xc000059f50 pc=0x447cce 
221
     runtime.goparkunlock(...) 
222
     	runtime/proc.go:404 
223
     runtime.(*scavengerState).park(0x142d760) 
224
     	runtime/mgcscavenge.go:425 +0x49 fp=0xc000059fa0 sp=0xc000059f70 pc=0x42b6c9 
225
     runtime.bgscavenge(0x0?) 
226
     	runtime/mgcscavenge.go:658 +0x59 fp=0xc000059fc8 sp=0xc000059fa0 pc=0x42bc79 
227
     runtime.gcenable.func2() 
228
     	runtime/mgc.go:201 +0x25 fp=0xc000059fe0 sp=0xc000059fc8 pc=0x421d65 
229
     runtime.goexit() 
230
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc000059fe8 sp=0xc000059fe0 pc=0x47d041 
231
     created by runtime.gcenable in goroutine 1 
232
     	runtime/mgc.go:201 +0xa5 
233
     goroutine 17 [finalizer wait, 2 minutes]: 
234
     runtime.gopark(0x0?, 0xc000110498?, 0x50?, 0x12?, 0x1000000010?) 
235
     	runtime/proc.go:398 +0xce fp=0xc0042b6e28 sp=0xc0042b6e08 pc=0x447cce 
236
     runtime.runfinq() 
237
     	runtime/mfinal.go:193 +0x107 fp=0xc0042b6fe0 sp=0xc0042b6e28 pc=0x420e47 
238
     runtime.goexit() 
239
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc0042b6fe8 sp=0xc0042b6fe0 pc=0x47d041 
240
     created by runtime.createfing in goroutine 1 
241
     	runtime/mfinal.go:163 +0x3d 
242
     goroutine 209 [GC worker (idle)]: 
243
     runtime.gopark(0x1472600?, 0x2?, 0x8d?, 0xd6?, 0xc1cf80?) 
244
     	runtime/proc.go:398 +0xce fp=0xc00044bf50 sp=0xc00044bf30 pc=0x447cce 
245
     runtime.gcBgMarkWorker() 
246
     	runtime/mgc.go:1293 +0xe5 fp=0xc00044bfe0 sp=0xc00044bf50 pc=0x423a85 
247
     runtime.goexit() 
248
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc00044bfe8 sp=0xc00044bfe0 pc=0x47d041 
249
     created by runtime.gcBgMarkStartWorkers in goroutine 144 
250
     	runtime/mgc.go:1217 +0x1c 
251
     goroutine 197 [select]: 
252
     runtime.gopark(0xc158a53fb0?, 0x2?, 0x2?, 0x0?, 0xc158a53f6c?) 
253
     	runtime/proc.go:398 +0xce fp=0xc158a53dc0 sp=0xc158a53da0 pc=0x447cce 
254
     runtime.selectgo(0xc158a53fb0, 0xc158a53f68, 0x0?, 0x0, 0x2?, 0x1) 
255
     	runtime/select.go:327 +0x725 fp=0xc158a53ee0 sp=0xc158a53dc0 pc=0x458cc5 
256
     cmd/compile/internal/gc.compileFunctions.func3() 
257
     	cmd/compile/internal/gc/compile.go:154 +0x126 fp=0xc158a53fe0 sp=0xc158a53ee0 pc=0xc6eb86 
258
     runtime.goexit() 
259
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc158a53fe8 sp=0xc158a53fe0 pc=0x47d041 
260
     created by cmd/compile/internal/gc.compileFunctions in goroutine 1 
261
     	cmd/compile/internal/gc/compile.go:147 +0xf1 
262
     goroutine 210 [GC worker (idle)]: 
263
     runtime.gopark(0x378ef43b443?, 0x2?, 0xd8?, 0xc0?, 0x0?) 
264
     	runtime/proc.go:398 +0xce fp=0xc00044b750 sp=0xc00044b730 pc=0x447cce 
265
     runtime.gcBgMarkWorker() 
266
     	runtime/mgc.go:1293 +0xe5 fp=0xc00044b7e0 sp=0xc00044b750 pc=0x423a85 
267
     runtime.goexit() 
268
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc00044b7e8 sp=0xc00044b7e0 pc=0x47d041 
269
     created by runtime.gcBgMarkStartWorkers in goroutine 144 
270
     	runtime/mgc.go:1217 +0x1c 
271
     goroutine 231898 [select]: 
272
     runtime.gopark(0xc000054fb0?, 0x2?, 0x4?, 0x0?, 0xc000054f6c?) 
273
     	runtime/proc.go:398 +0xce fp=0xc000054dc0 sp=0xc000054da0 pc=0x447cce 
274
     runtime.selectgo(0xc000054fb0, 0xc000054f68, 0xc0009c07e0?, 0x0, 0xccb4c0?, 0x1) 
275
     	runtime/select.go:327 +0x725 fp=0xc000054ee0 sp=0xc000054dc0 pc=0x458cc5 
276
     cmd/compile/internal/gc.compileFunctions.func3() 
277
     	cmd/compile/internal/gc/compile.go:154 +0x126 fp=0xc000054fe0 sp=0xc000054ee0 pc=0xc6eb86 
278
     runtime.goexit() 
279
     	runtime/asm_amd64.s:1650 +0x1 fp=0xc000054fe8 sp=0xc000054fe0 pc=0x47d041 
280
     created by cmd/compile/internal/gc.compileFunctions in goroutine 1 
281
     	cmd/compile/internal/gc/compile.go:147 +0xf1 
282
  
283
  
284
 Error: Preview failed: [resource plugin random-4.13.2] installing 
285
 [resource plugin docker-4.4.3] installing 
286
 [resource plugin gcp-6.67.0] installing 
```

## Steps to reproduce

1. Have Pulumi Deployments configured.
2. Create a branch that triggers preview/update.
3. Pulumi Deployments eventually reports `out of memory`

## Context (Environment)

This blocks all our deployments through CI.

**Comment by EvanBoyle** [comment] 2023-10-16 21:05
@deni64k thanks for reporting this. Do you have a program that reproduces this? 

I tried building a few simple programs with go + AWS and GCP and did not hit this error. If you have a repro we would love to run some profiling!

I'd also be curious to understand if you see this in another build environment that is limited to 8GB of RAM (for instance github actions, or a docker container limited to 8GB).

**Comment by t0yv0** [comment] 2023-10-16 21:45
I'm sorry you are having this experience! Would also love to reproduce this in some form. 

Just in case this helps, noting that Go memory use during the compile phase can be reduced using GOMAXPROCS=1 (at the expense of longer compilation times). Since it appears that `go build` is running out of memory, this may be relevant. But perhaps it is a long shot. Other processes may contend for system memory as well, and it just happens to fail in `go build` phase. 

On a very small program using pulumi-gcp I'm getting this memory utilization, under 0.25 GB, clearly does not explain allocating 8GB:

```
 pulumi                 28.4 MB 
 pulumi-go.324594024    6.3 MB  
 pulumi-language-go     14.8 MB 
 pulumi-resource-gcp    101.0 MB
 pulumi-resource-gcp    106.3 MB	
```
 
How the above is collected: insert a time.Sleep() in the Go program, run pulumi up, observe memory usage in Activity Monitor (Mac OS).

I'm not seeing significant Go compiler memory use on the program I'm trying this on.

**Comment by t0yv0** [comment] 2023-10-16 21:58
Curious also if this issue perchance is associated with a very large state? 

```
pulumi stack export --file state.json
du -sh state.json # what is the value reported here?
```

**Comment by deni64k** [comment] 2023-10-24 12:25
Sorry for the delay.

I tried to reproduce it locally and found out that linking `github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/compute` consumes 8+ GB.
I tried to roll back to `pulumi/pulumi:3.86.0` and golang 1.20 and observed the same RAM consumption.

What I did:
```
$ docker run -ti --rm -v $(pwd):/app --entrypoint /bin/sh --workdir /app/projects/backend pulumi/pulumi:3.89.0
# GOMAXPROCS=1 go build -x -v
```

I've tried `-buildmode=c-shared`, but got the same RAM consumption again.
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/107541/3abef284-a680-4327-8efa-c500bcf1dc09)
![image](https://github.com/pulumi/pulumi-cloud-requests/assets/107541/1870f0ec-0932-4928-b68f-f1667f4876ef)

**Comment by deni64k** [comment] 2023-10-24 12:44
Minimal program to reproduce:

```sh
$ cat <<EOF >main.go
package main

import (
        "github.com/pulumi/pulumi-gcp/sdk/v6/go/gcp/compute"
)

func main() {
        _ = compute.NewNetworkPeeringRoutesConfig
}
EOF
$ go mod init bomb
$ go mod tidy
$ docker run -ti --rm -v $(pwd):/app -e GOMAXPROCS=1 --workdir /app --entrypoint /usr/bin/env pulumi/pulumi:3.89.0 go build -v
```

![image](https://github.com/pulumi/pulumi-cloud-requests/assets/107541/c80b4982-2eb5-457d-a4f5-25cde74626a5)

**Comment by t0yv0** [comment] 2023-10-24 14:09
Excellent, thank you very much I can reproduce it. I filed https://github.com/pulumi/pulumi-gcp/issues/1283 .

**Comment by cleverguy25** [comment] 2024-04-15 18:57
We have the go specific issue to track next steps there, closing this one as not currently an issue.

**Closed as completed by cleverguy25** 2024-04-15 18:57 UTC
Labels: kind/bug, resolution/fixed, awaiting-upstream, customer/feedback
